// src/data.js
export const eventsData = [
    {
      id: 1,
      title: "React Workshop",
      description: "Learn the basics of React",
      category: "Tech",
      date: "2024-10-20",
      availableSeats: 50,
      price: 100,
    },
    {
      id: 2,
      title: "Music Concert",
      description: "Enjoy live music by top artists",
      category: "Music",
      date: "2024-11-10",
      availableSeats: 200,
      price: 50,
    },
    {
        id: 3,
        title: "AI & Machine Learning Conference",
        description: "Join industry experts for a full-day conference on AI and machine learning trends.",
        category: "Tech",
        date: "2024-11-15",
        availableSeats: 150,
        price: 250,
      },
      {
        id: 4,
        title: "Yoga for Beginners",
        description: "A peaceful yoga session to introduce you to the basics of yoga and mindfulness.",
        category: "Fitness",
        date: "2024-10-25",
        availableSeats: 30,
        price: 25,
      },
      {
        id: 5,
        title: "Coding Bootcamp",
        description: "A 3-day coding bootcamp for beginners, covering HTML, CSS, and JavaScript.",
        category: "Tech",
        date: "2024-11-20",
        availableSeats: 75,
        price: 150,
      },
      {
        id: 6,
        title: "Rock Concert",
        description: "Experience a high-energy performance by top rock bands from around the country.",
        category: "Music",
        date: "2024-12-05",
        availableSeats: 2,
        price: 80,
      },
      {
        id: 7,
        title: "Marathon Training",
        description: "Join us for a training session focused on preparing you for your first marathon.",
        category: "Fitness",
        date: "2024-10-30",
        availableSeats: 50,
        price: 20,
      },
      {
        id: 8,
        title: "Photography Workshop",
        description: "Learn how to take stunning photos using your DSLR or smartphone camera.",
        category: "Creative",
        date: "2024-11-25",
        availableSeats: 40,
        price: 75,
      },
      {
        id: 9,
        title: "Digital Marketing Seminar",
        description: "A seminar on the latest trends in digital marketing and how to implement them.",
        category: "Business",
        date: "2024-11-12",
        availableSeats: 10,
        price: 120,
      },
      {
        id: 10,
        title: "Fitness Bootcamp",
        description: "A high-intensity fitness bootcamp for those looking to push their physical limits.",
        category: "Fitness",
        date: "2024-10-20",
        availableSeats: 25,
        price: 30,
      }
  ];
  